services:
  Pfilsx\DataGrid\Grid\DataGridFactoryInterface:
    class: Pfilsx\DataGrid\Grid\DataGridFactory
    arguments: ['@doctrine', '@router', '@twig', '@request_stack', '@data_grid.configuration']
